# Generated by Django 5.1.7 on 2025-05-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_servico_descricao_alter_servico_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='avaliacao',
            field=models.FloatField(default=0, verbose_name='Avaliação Média'),
        ),
        migrations.AddField(
            model_name='servico',
            name='num_avaliacoes',
            field=models.IntegerField(default=0, verbose_name='Número de Avaliações'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='index.servico')),
            ],
        ),
    ]
