# Generated by Django 5.1.7 on 2025-03-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='contacto',
            new_name='telefone',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
