# Generated by Django 5.1.7 on 2025-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_remove_comentario_autor_remove_comentario_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='classificacao',
            field=models.IntegerField(default=0),
        ),
    ]
