# Generated by Django 5.1.7 on 2025-05-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_comentario_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_prestados', to='perfil.perfil'),
        ),
    ]
