# Generated by Django 5.1.7 on 2025-03-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_rename_contacto_perfil_telefone_perfil_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
