# Generated by Django 5.1.7 on 2025-05-11 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('perfil', '0010_alter_servico_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation', to='perfil.servico'),
        ),
    ]
