# Generated by Django 5.1.7 on 2025-03-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('classificacao', models.FloatField()),
                ('imagem', models.ImageField(upload_to='especialistas/')),
            ],
        ),
    ]
