# Generated by Django 5.1.7 on 2025-04-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_servico_descricao_servico_categoria_and_more'),
        ('perfil', '0006_perfil_foto_perfil_alter_servico_prestador'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoria do Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto Telefónico'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/', verbose_name='Foto do Serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Prestador'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil', verbose_name='Prestador de Serviço'),
        ),
    ]
