# Generated by Django 5.1.7 on 2025-05-02 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_servico_avaliacao_servico_num_avaliacoes_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='num_avaliacoes',
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Classificação')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='index.servico')),
            ],
        ),
    ]
