# Generated by Django 5.1.7 on 2025-05-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_servico_avaliacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
